### PR TITLE
Separate image.go into an image package

### PR DESCRIPTION
**Pull request by zombiezen**
This allows users of the package to install SDL_image separately from the main SDL library.

### CODE REVIEW

**Comment by adam000** [comment]
CR :+1:

**Comment by adam000** [comment]
1) Merge conflict, sadface
2) I would prefer that the showimage folder has a `.gitignore` to ignore built binaries. Would you kindly add that?

**Comment by zombiezen** [comment]
gitignore added. Should I resolve merge conflict by merging master?

**Comment by adam000** [comment]
Yup

**Comment by zombiezen** [comment]
Done.

**Comment by adam000** [comment]
Woot!

CR :+1:

**Pull request merged**
