### PR TITLE
Simple main thread

### PR DESCRIPTION
**Pull request by zombiezen**
Allow optional, simple main thread management using `sdl.Do` and `sdl.Main`.

### CODE REVIEW

**Comment by adam000** [comment]
Merge conflicts, but LGTM

**Comment by zombiezen** [comment]
I'm pushing the merge here, but I haven't tested the changes to showimage yet.  Either wait for me to test or test yourself before merging.

**Comment by zombiezen** [comment]
Tested locally. Good to go.

**Comment by adam000** [comment]
Tested on OS X 10.9!

**Pull request merged**
